#!/bin/bash

SCENARIOS="symfony2 symfony3 symfony4"
AUTOLOAD_DIRECTORIES='src tests'

platform_php_symfony2='5.4'
platform_php_symfony3='5.6'

requirement_symfony2='symfony/yaml:^2.8'
requirement_symfony3='symfony/yaml:^3'
requirement_symfony4='symfony/yaml:^4'
